### PR TITLE
www-client/firefox: fix segfault with arm

### PR DESCRIPTION
**Pull request by stefson**
This patch reverts the fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1238661, which is one of many fixes to enable the build of the android version of firefox with clang. It is as of firefox-59.0.2 not yet possible to build firefox with clang on arm/linux, but the fix for clang produces a segfault when firefox is build with gcc. 

Therefore I made the patch into a conditional statement, I hope it does work as intended to only apply when USE="-clang" and to not apply when USE="+clang"

### CODE REVIEW

**Comment by perfect7gentleman** [comment]
honestly speaking, I don't have possibility to maintain arm architecture.
If you want to, you can fork it.

**Comment by stefson** [comment]
I can take care of that, no problem! ;-) 
Just give me some sort of policy to work with, as to only use cond. statements for patches to fix arm stuff, or whatever suits you. It's possibly to build it:

firefox-59 0 2-arm-gcc7

(Also I have working beta-60 ebuild)

**Comment by perfect7gentleman** [comment]
I don't get it. What kind of policy?
And also, you'd better direct that request to gentoo's firefox maintainter to add arm support.

**Comment by stefson** [comment]
I meant it as an offer, so that I would take care of the arm specific fixes via pull requests for instance. Mozilla team is not doing it's job at the moment for unknown reaons, and it is anyway pointless to open bugs because there is no official rust in tree for arm. It is possible to emerge it with a simple fix, but also rust team is not really up for this.

**Comment by stefson** [comment]
Actually I really like your ebuild for the various patches, and compile switches fine tuning, but as you are in fast develope mode it is a bit difficult to keep up with a possible fork on my own. The changes should be non invasive if I make them conditionally.

**Comment by perfect7gentleman** [comment]
there is some policy.
1 - try to not modyfy eclass
2 - keep ebuild as much as close to one from main tree

try to make all modification in ebuild. if it's possible make one block that starts with 'if use arm'

**Comment by stefson** [comment]
fine, I'll ping you if the pr is ready to be merged.

**Comment by perfect7gentleman** [comment]
i close  this pr.
create new one.

**Pull request closed without merging**
